services:
  product-db:
    image: postgres:17-alpine
    container_name: microshop-product-db
    environment:
      POSTGRES_DB: microshop_products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data
    
  order-db:
    image: postgres:17-alpine
    container_name: microshop-order-db
    environment:
      POSTGRES_DB: microshop_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - order-db-data:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: microshop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: microshop
      RABBITMQ_DEFAULT_PASS: microshop
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  product-db-data:
  order-db-data:
  rabbitmq-data:
